{"name": "test_number_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 3", "trace": "self = <test_search_page.TestSearch object at 0x1029a12d0>\n\n    def test_number_3(self):\n>       assert 1 == 3\nE       assert 1 == 3\n\ntestcase/test_search_page.py:21: AssertionError"}, "start": 1662371708842, "stop": 1662371708843, "uuid": "14501a78-a681-4f10-bee2-1b3a99a58f97", "historyId": "7c659cc162fc15c64bb46bb67d84d35b", "testCaseId": "0080e1a7d0728201a1445ee9c4329685", "fullName": "testcase.test_search_page.TestSearch#test_number_3", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_search_page"}, {"name": "subSuite", "value": "TestSearch"}, {"name": "host", "value": "cjn"}, {"name": "thread", "value": "62810-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_search_page"}]}